---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
after_success:
  ["git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng", ".forge-releng/publish"]
env:
  global:
    - PUBLISHER_LOGIN=camptocamp
    - secure: "U9rgKr4SD4Ivrw6y0pehU1HpPmJPWJ6CdLuAdZhjbScFjM/ava3LG99MmbFm
MxuPXiSvTA7AGeD31IGT/gFH+mKfvOl4rQsMcIJHFb/7GU4Dsx/BwAENPqPO
iIVVK7WGr2KHqxaoB08lB3FO7JTEFNrd1RordvG9isnI9PhIn8s="
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
